### ISSUE TITLE
Relations with mediaman-suffixes

### ISSUE THREAD

**Issue by ioggstream** [ietf-wg-httpapi/mediatypes#67]
From media type ML

## Question

 I wonder if the authors of the I-D
draft-ietf-mediaman-suffixes will want to say something;

See #1 cc: @msporny

**Comment by ioggstream** [comment]
@msporny iiuc this I-D is independent from mediaman-suffixes do you see any issue here?

**Comment by msporny** [comment]
Yes, happy to provide some feedback. I've looked at both of these specs:

https://ietf-wg-httpapi.github.io/mediatypes/draft-ietf-httpapi-rest-api-mediatypes.html
https://ietf-wg-httpapi.github.io/mediatypes/draft-ietf-httpapi-yaml-mediatypes.html

The REST API mediatypes spec doesn't have anything out of the ordinary that I could see, so not much to say there. If there was a particular part of that spec that you felt needed feedback based on the draft-ietf-mediaman-suffixes draft, I'd be happy to look a bit more closely. For now, spec seems fine.

The YAML mediatype is of concern to the draft-ietf-mediaman-suffixes draft because of the +yaml structured syntax suffix and the possibility of a +ld+yaml mediatype in the future, which might be used with application/vc+ld+yaml or application/did+ld+yaml. Even in those cases, I see no problem with the structured syntax suffix registration nor how the processing rules are defined for the +yaml structured syntax suffix.

Both specifications seem fine from a cursory review. Please provide specific areas that you were hoping for feedback if the review above is not adequate. If you'd like me to send this review to the mailing list, please let me know and I can do that.

**Comment by ioggstream** [comment]
Thanks @msporny I think it's great! I will close with no action since there are no specific incompatibilities with the other spec!
