### ISSUE TITLE
jsonschema media types

### ISSUE THREAD

**Issue by ioggstream** [ietf-wg-httpapi/mediatypes#7]
## I expect

- jsonschema media type for json and yaml

application/schema+json #19 
application/schema-instance+json #19 
~application/schema+yaml~ moved to #18 

- [ ] fragment identifier
- [ ] specification document
- [ ] security considerations
- [x] file extension

Cc @jasondesrosiers @relequestual

It would be great to reserve the media type so that it can be used in the wild even before jsonschema is out.

Supporting versioning we can do Eg

application/schema+json; v=draft-2020

Thx++ R

**Comment by jdesrosiers** [comment]
Thanks, @ioggstream. I'll see if I can submit a PR for JSON Schema some time this week. Thanks for including us!

> It would be great to reserve the media type so that it can be used in the wild even before jsonschema is out.

We don't consider JSON Schema in a pre-release state. We only call releases "drafts" for historical reasons. And the media type has been used in the wild for years, which is why we want to get it officially registered!

**Comment by ioggstream** [comment]
about filename extension https://github.com/json-schema-org/json-schema-spec/issues/1130

**Comment by cjaccino** [comment]
Could we include registration of JSON Schema in YAML format as well?

- `application/json-schema+yaml` (or possibly just `application/schema+yaml`)
- `application/json-schema-instance+yaml` (if needed)  Would this be necessary if YAML supports JSON Pointer fragment styles in its registration?

**Comment by ioggstream** [comment]
@cjaccino could you please integrate your considerations in   #18 ?
