### ISSUE TITLE
ld+yaml media-type

### ISSUE THREAD

**Issue by ioggstream** [ietf-wg-httpapi/mediatypes#8]
## I expect

To register the `application/ld+yaml` mediatype.
This includes:

- [x] providing considerations about yaml features that are not round-trip safe when serializing to json, including
  - [x] Complex mapping keys, since keys must be str, int, float, bool or None, not tuple
  - [x] NaN, Infty not supported
- [x] providing considerations about yaml features that cannot be used since there is no json counterpart (eg. explicit typing `!!str`)

@dlongley @msporny @gkellogg

**Comment by msporny** [comment]
> To register the `application/ld+yaml` mediatype

Great! Please make sure it's completely round-trippable between `application/ld+json` :) -- creating any deviation would be problematic. That is, as much as it might be really awesome to use some of YAML's features that are different from JSON... doing so, in a non-round-trippable way, would probably hurt the initiative.

**Comment by ioggstream** [comment]
@msporny @pchampin @gkellogg first and foremost, thanks for your replies! I follow up the discussion here so that comments won't get lost if #9 will be superseeded by another PR.

Agree with @msporny : we need to identify the admissible yaml subset and to clarify that:
* some features won't be round-trip-safe;
* some features won't fit json anyway.

For example:

- comments won't be preserved;
- allowed datatypes: mappings, scalars, string, int, float, null, ...
- only one document `--- [...] ...`
- no explicit typing (eg. `!!str` ) but for simplicity, but we can discuss in admitting types
- anchors and merge-keys allowed

I saw you have here a quite [long list of examples](https://github.com/w3c/json-ld-syntax/tree/main/yaml)...
do you already have a list of those features?

**Comment by gkellogg** [comment]
Those examples were created automatically by the script that validates examples in the spec, simply re-serializing them in YAML. No real work has gone in to specifically identify the YAML subset, but a YAML-LD spec should do so.

As JSON-LD specifically relies on an internal representation using Infra types, and we can expect other -LD variations (e.g, CBOR-LD) a future version of a core JsON-LD spec may provide some extension points for non-JSON data types, but that is entirely speculative.

**Comment by ioggstream** [comment]
@gkellogg @msporny I stubbed some considerations here https://github.com/ietf-wg-httpapi/mediatypes/pull/15/files

> internal representation using Infra types

how does this differ with RFC8259

> extension points for non-JSON data types

shouldn't any alternative representation have a well-defined mapping to JSON?

**Comment by pchampin** [comment]
> how does this differ with RFC8259

INFRA defines an abstract data model ; RFC8259 (JSON) defines an exchange format. Granted, the boundary a bit blurry: first, because JSON is based on JS, and therefore is often assumed to describe JS's data format. Second, because RFC8259 has a number of remarks about interoperability, which somehow constrain the underlying data formats used by JSON implementations. 

> shouldn't any alternative representation have a well-defined mapping to JSON?

That would make sense if JSON was a data model, which it is not (strictly speaking). INFRA, on the other hand is.

**Comment by ioggstream** [comment]
>> shouldn't any alternative representation have a well-defined mapping to JSON
> That would make sense if JSON was a data model

I mean that the infra spec defines a way to  [convert an infra value to a json compatible javascript value](https://infra.spec.whatwg.org/#convert-an-infra-value-to-a-json-compatible-javascript-value) for a [string](https://infra.spec.whatwg.org/#string), [boolean](https://infra.spec.whatwg.org/#boolean), number, null, [list](https://infra.spec.whatwg.org/#list), or [string](https://infra.spec.whatwg.org/#string)-keyed [map](https://infra.spec.whatwg.org/#ordered-map).

While extension points can be difficult to manage with JSON, yaml could define specific tags (eg. `!!infra:mynewtype` ) and the associated syntax for that. 

As of now, I think it would be beneficial trying to describe the current json mapping and address extension points when they'll be defined.

Probably, instead of restricting how to use yaml for encoding json-ld objects, it is better to provide guidance in what will be interoperable or not with respect to JSON, and leave the choice to the user. cc: @msporny

**Comment by msporny** [comment]
> Probably, instead of restricting how to use yaml for encoding json-ld objects, it is better to provide guidance in what will be interoperable or not with respect to JSON, and leave the choice to the user. cc: @msporny

I'll merely note that the Decentralized Identifier WG ended up having to define the core data model in INFRA and then demonstrate mappings to JSON and JSON-LD. There was work to map the core data model to CBOR, but that work failed due to disinterest.

See this section on core data model that uses INFRA:

https://www.w3.org/TR/did-core/#data-model

... and how we mapped it to JSON:

https://www.w3.org/TR/did-core/#production

... which the JSON-LD representation then built on top of:

https://www.w3.org/TR/did-core/#production-0

The end result, IMHO, was an awful mess... we should have never done it. A few loud opinions in the WG wanted it, and it was clear that there were going to be formal objections if we didn't do it, so we tried the experiment and I did my best to make it make sense in the specification. I have always been of the opinion that we should've just used the JSON-LD data model and be done with it (it had direct mappings to JSON, CBOR, etc.)... so, just a word of warning for anyone that wants to try to get INFRA working w/ JSON-LD... it's possible, but the end result is hard for many to grasp and understand... though, it's not much better for RDF, is it? :)

**Comment by pchampin** [comment]
@msporny although a sympathize with your pain re. DID, I think the problem here is very different.

If YAML is to be used as a representation for a JSON-LD document, then one has to specify how to represent [JSON-LD internal representation](https://www.w3.org/TR/json-ld11-api/#dfn-internal-representation) in YAML. And that internal representation is based on INFRA.

For the DID core model, I agree with you that it would have been better to define it in terms of the [JSON-LD data model](https://www.w3.org/TR/json-ld/#data-model), which can then be serialized in JSON, and inherit form all other JSON-LD representations to come, including YAML...

**Comment by pchampin** [comment]
@msporny I'm confused

> JSON-LD already has an abstract data model defined, why can't YAML-LD just use that: https://w3c.github.io/json-ld-syntax/#data-model

(...)

> This is the approach we took with CBOR-LD -- just define how to map to/from JSON-LD and you're done -- (and I fully admit that some might find the approach controversial).

As I read it, CBOR-LD defines how to map to/from [JSON-LD's **internal representation**](https://www.w3.org/TR/json-ld11/#dfn-internal-representation): it works at the level of maps, key-value pairs... not at the level of nodes, arcs and graphs, as described by the [data model](https://www.w3.org/TR/json-ld11/#data-model).

So I think we are in violent agreement here :)

> I will admit that if something changed drastically in JSON-LD 1.1 that makes this impossible, I'm unaware of it. :)

I don't think that's the case :-)

Although the notion of "internal representation" was not explicitly defined in JSON-LD 1.0, it was [implictly there](https://www.w3.org/TR/2014/REC-json-ld-20140116/#h3_general-terminology), but referred simply to [RFC4627](https://datatracker.ietf.org/doc/html/rfc4627). Moving from RFC4627's terminology to INFRA's terminology was deemed cleaner because, again, RFC4627 does not really define a data model (only a syntax), while INFRA does.

**Comment by gkellogg** [comment]
If I were to revisit anything in the JSON-LD data model, it would be the interpretation of JSON numbers to allow for decimal values. As it is now, JSON numbers are either interpreted as integers (long) or doubles based on the range of the number. But, in JSON-LD 1.1, we use The JSON Canonicalization Scheme ([RFC8785](https://www.w3.org/TR/json-ld11/#bib-rfc8785)) as a way to represent numbers in the `rdf:JSON` datatype serialization, which allows for a serialization form of either integer, decimal, or double. This really only comes into play in JSON-LD when creating RDF literals from native JSON numbers (something which is generally a bad design point, but is there to allow a reasonable interpretation of native JSON forms), but could also come into play when representing those numbers in the data model, and thus in serializations to forms such as YAML.

**Comment by darrelmiller** [comment]
In the [OpenAPI specification](https://spec.openapis.org/oas/v3.1.0#format), we limit the use of YAML to the "JSON Schema" https://yaml.org/spec/1.2.2/#json-schema  (not to be confused with [JSON Schema](https://json-schema.org/) ).  Specifying this constraint has proven sufficient for us to ensure tooling can roundtrip between YAML and JSON.

**Comment by ioggstream** [comment]
@darrelmiller we will address the issues with "yaml json schema"  (see the interoperability considerations), so that might need tweaking the OAS spec too.

**Comment by ioggstream** [comment]
Moved to https://github.com/json-ld/yaml-ld/
